### ISSUE TITLE
NullReferenceException when I trying to add TextBoxField

### ISSUE THREAD

**Issue by fedorino-alex** [aspose-free-consulting/projects#28]
Hey, my project is running in Docker container based on Linux Alpine, and my task is highlight some text fragment like a hyperlink and make popup message on hovering this link. I decided to use TextBoxField, placed over text fragment because I need it to work on Google Chrome and Adobe Acrobat Reader. Also I do some decorations, like border, background color, **Arial font** and etc. 

But, when I put the text into Value property - I get System.NullReferenceException.
Stack trace is here: ```
System.NullReferenceException: Object reference not set to an instance of an object.
   at #=zDwGbcB4GP$EtqQOcoR5PHQgAvB5rx0Ym5iSnCDo7WVe2.#=zgkm65jc=(#=zu24DCOrH$PlhJSXxRTH0iOE= #=zTwpRwts=, Boolean #=zt9wEeYbqIXr_, Boolean #=zGsWDMXA=, Boolean #=zgPLU00Q=)
   at #=zDwGbcB4GP$EtqQOcoR5PHQgAvB5rx0Ym5iSnCDo7WVe2.#=zGTnAb3Y9PFUslG1aXw==(#=zQ1QRfnYGY_Cf6TD93PUWH$jxnz8y1t0CDMeG_q0= #=zu1HvU98=, #=zu24DCOrH$PlhJSXxRTH0iOE= #=zTwpRwts=, Boolean #=zgPLU00Q=, String& #=zGba0mfQ=)
   at #=z6FZ0vcBBFfvzvhyPkNKS0DqC$XUWu4G4lxQdd3j0j4jYXAb4D$82BkE=.#=zoa1p39JZSdZI(String #=z7ppX2lY=, #=zQ1QRfnYGY_Cf6TD93PUWH$jxnz8y1t0CDMeG_q0= #=zu1HvU98=, #=zVAG$DdjlHTykOyjIWR019U8hU$Vju69fsA==& #=zlcc2Fm8=, #=zXXJGE6zwmDAguaHaPQVRo9KbuV7h6HXauJIoqXHGHZwm& #=zi2$EDyAUqVcB, String& #=zUfq9SVUIVubm)
   at Aspose.Pdf.Forms.TextBoxField.#=zwy2DxGsDrKE3(#=zE8BHI3k3B4g8 #=zj0KBaOc=, Annotation #=z8PqDbq0=)
   at Aspose.Pdf.Annotations.WidgetAnnotation.#=zIGPt4H4=(Annotation #=z8PqDbq0=)
   at Aspose.Pdf.Forms.Field.#=zx5fFGUg=(String #=z4MuNd_4=)
   at Aspose.Pdf.Forms.Field.set_Value(String value)
   at Aspose.Pdf.Forms.TextBoxField.set_Value(String value)
   at PdfEnriching.Services.Implementation.TextBoxFieldToolTipBuilder.SetUp(TextBoxField field, String value) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/TextBoxFieldToolTipBuilder.cs:line 69
   at PdfEnriching.Services.Implementation.TextBoxFieldToolTipBuilder.Build(PageInfo pageInfo, Page page, Rectangle rectangle, Link link, Boolean mostRecent) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/TextBoxFieldToolTipBuilder.cs:line 50
   at PdfEnriching.Services.Implementation.PdfEnrichingService.AddTooltip(Link link, Boolean mostRecent, ButtonField button, TextFragment fragment, Document document) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/PdfEnrichingService.cs:line 398
   at PdfEnriching.Services.Implementation.PdfEnrichingService.EnrichPdfDocument(IEnrichingContext context, IEnumerable`1 links, Document document, CancellationToken cancellationToken) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/PdfEnrichingService.cs:line 346
   at PdfEnriching.Services.Implementation.PdfEnrichingService.Enrich(IEnrichingContext context, LookupResult[] lookupResults, CancellationToken cancellationToken) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/PdfEnrichingService.cs:line 197
   at PdfEnriching.Services.Implementation.PdfEnrichingService.DoWorkAsync(QueueInfo queueInfo, CancellationToken cancellationToken) in /builds/agent1/37/s/src/PdfEnriching/Services/Implementation/PdfEnrichingService.cs:line 83
   at IHS.Services.DocumentProcessing.Ticker.DocumentProcessingTicker.DoWorkAsync(CancellationToken cancellationToken)```

I cannot upderstand real reason of this error, I'm feeling it is related to font, we have installed it inside container (I can provide Dockerfile to you).

Can you help me?

**Comment by asadalikhan90** [comment]
@fedorino-alex 

We have responded to your [similar inquiry](https://forum.aspose.com/t/208141/2) over Aspose.PDF forum. You may please followup there.
